from database.db import SessionLocal
from database.models import Transporter, Trip, DieselToken, User
from utils.security import hash_password

db = SessionLocal()


def seed():
    # create test users
    users = [("sales", "pump_salesman"), ("ops", "pump_ops")]
    for u in users:
        if not db.query(User).filter_by(username=u[0]).first():
            db.add(User(username=u[0], password=hash_password("pass"), role=u[1]))
    db.commit()

    # create transporter
    from database.models import Truck

    t = Transporter(name="Overdraft Test Transport", phone="999999999", balance=10000)
    db.add(t)
    db.commit()
    db.refresh(t)

    # create truck
    truck = Truck(transporter_id=t.id, vehicle_number="TEST01")
    db.add(truck)
    db.commit()
    db.refresh(truck)

    # create trip
    tr = Trip(
        truck_id=truck.id,
        origin="Site A",
        destination="Site B",
        material="Iron",
        qty_mt=50,
        freight_amount=5000,
        remaining_balance=5000,
        driver_name="T",
        driver_number="1",
    )
    db.add(tr)
    db.commit()
    db.refresh(tr)

    # create token mock
    # Wait, token is generated by token_service. We can just inject it.
    # Actually, we should simulate the deduction. But for testing the *redemption* logic, we just need the DB record.
    tok = DieselToken(
        token_uuid="TOKEN-OVERDRAFT",
        trip_id=tr.id,
        transporter_id=t.id,
        value=1000.0,
        remaining_value=1000.0,
        status="issued",
    )
    db.add(tok)
    db.commit()

    print(" Seeded test token TOKEN-OVERDRAFT")


if __name__ == "__main__":
    seed()
